import type { Instructor, FitnessClass } from '@/types';

export const INSTRUCTORS: Instructor[] = [
  {
    id: 'cams',
    name: 'Cams Rivera',
    avatar: '👩‍🦱',
    bio: 'Co-founder of Evolve. Over a decade of experience in pole fitness and aerial arts. Cams brings fierce energy and empowering movement to every class.',
    specialty: 'Pole Fitness, Exole (Exotic Pole)',
    musicStyle: 'R&B & Deep House',
    playlist: 'Cams Power Hour',
    instagram: '@camsevolve',
    totalStudents: 1240,
    rating: 4.98,
  },
  {
    id: 'tweetie',
    name: 'Tweetie Bullecer',
    avatar: '👩‍🦰',
    bio: 'Founder of Evolve Pole Fitness & Aerial Arts. Tweetie built the studio on the belief that pole fitness is empowering, joyful, and artistic for women of all ages.',
    specialty: 'Aerial Sling, Yoga, Pole Fitness',
    musicStyle: 'Ambient Flow & Pop',
    playlist: 'Tweetie Flow Sessions',
    instagram: '@tweetieevolve',
    totalStudents: 1580,
    rating: 4.99,
  },
  {
    id: 'alex',
    name: 'Alex Tran',
    avatar: '🧑‍🦲',
    bio: 'Former professional dancer turned aerial coach. Alex brings athleticism, creativity, and precision to every aerial and chair session.',
    specialty: 'Aerial Sling, Sexy Chair',
    musicStyle: 'Latin Fusion & Afrobeats',
    playlist: 'Alex Heat Check',
    instagram: '@alexevolve',
    totalStudents: 650,
    rating: 4.92,
  },
];

function addDays(base: Date, days: number): string {
  const d = new Date(base);
  d.setDate(d.getDate() + days);
  // Skip Tuesdays — if the computed date falls on a Tuesday, push forward one day
  if (d.getDay() === 2) {
    d.setDate(d.getDate() + 1);
  }
  return d.toISOString().split('T')[0];
}

const today = new Date();
today.setHours(0, 0, 0, 0);

// If today is Tuesday, shift seed start to Wednesday
const seedBase = new Date(today);
if (seedBase.getDay() === 2) {
  seedBase.setDate(seedBase.getDate() + 1);
}

export const SEED_CLASSES: FitnessClass[] = [
  // Day 0 — today (or next non-Tuesday)
  {
    id: 'class-001',
    title: 'Pole Fitness Basics',
    type: 'Pole Fitness',
    instructor: INSTRUCTORS[0],
    date: addDays(seedBase, 0),
    time: '9:00 AM',
    duration: 60,
    totalSpots: 8,
    bookedSpots: [1, 3, 5],
    price: 600,
    level: 'All Levels',
    description: 'Learn the foundations of pole fitness — grip technique, basic spins, and confidence-building movement for all body types.',
    tags: ['Pole Fitness', 'Beginner-Friendly', 'Strength'],
  },
  {
    id: 'class-002',
    title: 'Aerial Sling Flow',
    type: 'Aerial Sling',
    instructor: INSTRUCTORS[1],
    date: addDays(seedBase, 0),
    time: '11:00 AM',
    duration: 60,
    totalSpots: 8,
    bookedSpots: [1, 2, 3, 4, 5, 6, 7, 8],
    price: 600,
    level: 'All Levels',
    description: 'Float and flow on the aerial sling. Build upper body strength while learning graceful transitions and poses.',
    tags: ['Aerial Sling', 'Flow', 'Upper Body'],
  },
  {
    id: 'class-003',
    title: 'Exole (Exotic Pole)',
    type: 'Exole',
    instructor: INSTRUCTORS[0],
    date: addDays(seedBase, 0),
    time: '2:00 PM',
    duration: 60,
    totalSpots: 8,
    bookedSpots: [1, 2],
    price: 600,
    level: 'Intermediate',
    description: 'Move boldly. Express freely. Exotic pole combines sensual movement, floorwork, and pole technique into fierce choreography.',
    tags: ['Exole', 'Exotic Pole', 'Choreography'],
  },
  {
    id: 'class-004',
    title: 'Evening Yoga',
    type: 'Yoga',
    instructor: INSTRUCTORS[1],
    date: addDays(seedBase, 0),
    time: '5:00 PM',
    duration: 60,
    totalSpots: 12,
    bookedSpots: [1, 3, 5],
    price: 550,
    level: 'Beginner',
    description: 'Wind down with a restorative yoga flow. Stretch, breathe, and reconnect after a long day.',
    tags: ['Yoga', 'Mindfulness', 'Recovery'],
  },

  // Day 1
  {
    id: 'class-005',
    title: 'Sexy Chair',
    type: 'Sexy Chair',
    instructor: INSTRUCTORS[2],
    date: addDays(seedBase, 1),
    time: '10:00 AM',
    duration: 60,
    totalSpots: 10,
    bookedSpots: [1, 4, 7],
    price: 600,
    level: 'All Levels',
    description: 'Confidence, flow, and fierce movement. Use the chair as your stage and let your body tell the story.',
    tags: ['Sexy Chair', 'Dance', 'Confidence'],
  },
  {
    id: 'class-006',
    title: 'Pole Fitness Intermediate',
    type: 'Pole Fitness',
    instructor: INSTRUCTORS[0],
    date: addDays(seedBase, 1),
    time: '1:00 PM',
    duration: 60,
    totalSpots: 8,
    bookedSpots: [2, 5, 8],
    price: 600,
    level: 'Intermediate',
    description: 'Level up your pole game — inversions, combos, and strength holds for movers ready to push further.',
    tags: ['Pole Fitness', 'Intermediate', 'Inversions'],
  },
  {
    id: 'class-007',
    title: 'Aerial Sling Kids',
    type: 'Aerial Sling Kids',
    instructor: INSTRUCTORS[1],
    date: addDays(seedBase, 1),
    time: '3:00 PM',
    duration: 45,
    totalSpots: 6,
    bookedSpots: [1, 2, 3],
    price: 600,
    level: 'Beginner',
    description: 'Little bodies, fearless spirits. A safe and playful aerial sling class designed for kids ages 6–12.',
    tags: ['Aerial Sling Kids', 'Children', 'Fun'],
  },

  // Day 2
  {
    id: 'class-008',
    title: 'Pole Fitness All Levels',
    type: 'Pole Fitness',
    instructor: INSTRUCTORS[0],
    date: addDays(seedBase, 2),
    time: '9:00 AM',
    duration: 60,
    totalSpots: 8,
    bookedSpots: [],
    price: 600,
    level: 'All Levels',
    description: 'An open-level pole fitness session — beginners learn the basics while advanced movers refine their flow.',
    tags: ['Pole Fitness', 'All Levels', 'Community'],
  },
  {
    id: 'class-009',
    title: 'Aerial Sling Strength',
    type: 'Aerial Sling',
    instructor: INSTRUCTORS[2],
    date: addDays(seedBase, 2),
    time: '11:00 AM',
    duration: 60,
    totalSpots: 8,
    bookedSpots: [1, 2, 3, 4, 5, 6],
    price: 600,
    level: 'Intermediate',
    description: 'Push your aerial limits with strength-focused sequences, drops, and dynamic transitions.',
    tags: ['Aerial Sling', 'Strength', 'Advanced'],
  },
  {
    id: 'class-010',
    title: 'Yoga & Restore',
    type: 'Yoga',
    instructor: INSTRUCTORS[1],
    date: addDays(seedBase, 2),
    time: '4:00 PM',
    duration: 75,
    totalSpots: 12,
    bookedSpots: [3, 6, 9],
    price: 550,
    level: 'All Levels',
    description: 'Restorative yoga with deep stretching, breathwork, and guided meditation. The antidote to your week.',
    tags: ['Yoga', 'Restore', 'Breathwork'],
  },

  // Day 3
  {
    id: 'class-011',
    title: 'Exole Choreography',
    type: 'Exole',
    instructor: INSTRUCTORS[0],
    date: addDays(seedBase, 3),
    time: '10:00 AM',
    duration: 60,
    totalSpots: 8,
    bookedSpots: [1, 3, 5, 7],
    price: 600,
    level: 'Intermediate',
    description: 'Learn a full exotic pole choreography routine. Floorwork, transitions, and performance-ready sequences.',
    tags: ['Exole', 'Choreography', 'Performance'],
  },
  {
    id: 'class-012',
    title: 'Sexy Chair Evening',
    type: 'Sexy Chair',
    instructor: INSTRUCTORS[2],
    date: addDays(seedBase, 3),
    time: '5:00 PM',
    duration: 60,
    totalSpots: 10,
    bookedSpots: [],
    price: 600,
    level: 'All Levels',
    description: 'An evening chair session to reconnect with your confidence and express through movement.',
    tags: ['Sexy Chair', 'Evening', 'Expression'],
  },

  // Day 4
  {
    id: 'class-013',
    title: 'Pole Fitness Advanced',
    type: 'Pole Fitness',
    instructor: INSTRUCTORS[0],
    date: addDays(seedBase, 4),
    time: '9:00 AM',
    duration: 60,
    totalSpots: 8,
    bookedSpots: [1, 2, 3, 4, 5, 6],
    price: 600,
    level: 'Advanced',
    description: 'For seasoned pole athletes — advanced combos, strength holds, and creative flow. Bring your A-game.',
    tags: ['Pole Fitness', 'Advanced', 'Elite'],
  },
  {
    id: 'class-014',
    title: 'Aerial Sling Kids Weekend',
    type: 'Aerial Sling Kids',
    instructor: INSTRUCTORS[1],
    date: addDays(seedBase, 4),
    time: '10:00 AM',
    duration: 45,
    totalSpots: 6,
    bookedSpots: [2, 4],
    price: 600,
    level: 'Beginner',
    description: 'Weekend aerial fun for kids! A playful session combining aerial skills, games, and creativity.',
    tags: ['Aerial Sling Kids', 'Weekend', 'Play'],
  },
];
