import type { Instructor, FitnessClass } from '@/types';

export const INSTRUCTORS: Instructor[] = [
  {
    id: 'cams',
    name: 'Cams Rivera',
    avatar: '👩‍🦱',
    bio: 'Founder of Evolve. 10+ years in pilates and movement therapy. Trained in LA and NYC, Cams brings high-energy, intentional movement to every class.',
    specialty: 'Full Body Reformer, Sculpt & Tone',
    musicStyle: 'Deep House Flows',
    playlist: 'Cams Morning Ritual',
    instagram: '@camsevolve',
    totalStudents: 1240,
    rating: 4.98,
  },
  {
    id: 'sarah',
    name: 'Sarah Lee',
    avatar: '👩‍🦰',
    bio: 'Certified yoga therapist and HIIT coach. Sarah is known for her curated playlists and seamless transitions that make hard work feel like dancing.',
    specialty: 'HIIT + Flow, Yoga',
    musicStyle: 'R&B Booty Sculpt',
    playlist: 'Sarah Sundown Sessions',
    instagram: '@sarahevolve',
    totalStudents: 870,
    rating: 4.95,
  },
  {
    id: 'alex',
    name: 'Alex Tran',
    avatar: '🧑‍🦲',
    bio: 'Former professional dancer turned wellness coach. Alex brings athleticism and precision to every session — be ready to feel the burn.',
    specialty: 'Mat Pilates, Sculpt',
    musicStyle: 'Afrobeats & Latin Fusion',
    playlist: 'Alex Heat Check',
    instagram: '@alexevolve',
    totalStudents: 650,
    rating: 4.92,
  },
];

function addDays(base: Date, days: number): string {
  const d = new Date(base);
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}

const today = new Date();
today.setHours(0, 0, 0, 0);

export const SEED_CLASSES: FitnessClass[] = [
  // Day 0 - today
  {
    id: 'class-001',
    title: 'Full Body Reformer',
    type: 'Reformer',
    instructor: INSTRUCTORS[0],
    date: addDays(today, 0),
    time: '7:00 AM',
    duration: 50,
    totalSpots: 12,
    bookedSpots: [1, 3, 5, 7, 9, 11],
    price: 35,
    level: 'All Levels',
    description: 'A full-body reformer session that targets every muscle group with controlled resistance and fluid movement.',
    tags: ['Reformer', 'Full Body', 'Strength'],
  },
  {
    id: 'class-002',
    title: 'HIIT + Flow',
    type: 'HIIT',
    instructor: INSTRUCTORS[1],
    date: addDays(today, 0),
    time: '9:30 AM',
    duration: 45,
    totalSpots: 16,
    bookedSpots: [2, 4, 6, 8, 10, 12, 14, 15, 16, 1, 3, 5, 7, 9, 11, 13],
    price: 35,
    level: 'Intermediate',
    description: 'High-intensity intervals paired with yoga flow recovery. Your heart rate will thank you... eventually.',
    tags: ['HIIT', 'Cardio', 'Flow'],
  },
  {
    id: 'class-003',
    title: 'Sculpt & Tone',
    type: 'Sculpt',
    instructor: INSTRUCTORS[2],
    date: addDays(today, 0),
    time: '12:00 PM',
    duration: 45,
    totalSpots: 14,
    bookedSpots: [1, 2],
    price: 35,
    level: 'All Levels',
    description: 'Lightweight resistance training focused on muscle endurance and body sculpting. Feel the shake, embrace the burn.',
    tags: ['Sculpt', 'Toning', 'Resistance'],
  },
  {
    id: 'class-004',
    title: 'Evening Yoga',
    type: 'Yoga',
    instructor: INSTRUCTORS[1],
    date: addDays(today, 0),
    time: '6:00 PM',
    duration: 60,
    totalSpots: 16,
    bookedSpots: [1, 3, 5],
    price: 35,
    level: 'Beginner',
    description: "Wind down with a candlelit vinyasa flow. Leave your stress at the door \u2014 this one's all release.",
    tags: ['Yoga', 'Mindfulness', 'Recovery'],
  },
  // Day 1
  {
    id: 'class-005',
    title: 'Mat Pilates Core',
    type: 'Mat Pilates',
    instructor: INSTRUCTORS[2],
    date: addDays(today, 1),
    time: '8:00 AM',
    duration: 50,
    totalSpots: 14,
    bookedSpots: [1, 4, 7],
    price: 35,
    level: 'Intermediate',
    description: 'Deep core work on the mat. No equipment needed — just your body, your breath, and your will.',
    tags: ['Mat', 'Core', 'Pilates'],
  },
  {
    id: 'class-006',
    title: 'Full Body Reformer',
    type: 'Reformer',
    instructor: INSTRUCTORS[0],
    date: addDays(today, 1),
    time: '10:00 AM',
    duration: 50,
    totalSpots: 12,
    bookedSpots: [2, 5, 8, 11],
    price: 35,
    level: 'Advanced',
    description: 'Advanced reformer challenge. This class is built for seasoned movers ready to level up.',
    tags: ['Reformer', 'Advanced', 'Strength'],
  },
  {
    id: 'class-007',
    title: 'HIIT Cardio Blast',
    type: 'HIIT',
    instructor: INSTRUCTORS[1],
    date: addDays(today, 1),
    time: '5:30 PM',
    duration: 40,
    totalSpots: 20,
    bookedSpots: [1, 2, 3, 4, 5],
    price: 35,
    level: 'Intermediate',
    description: 'Pure sweat. Pure power. 40 minutes of structured intervals that will leave you glowing.',
    tags: ['HIIT', 'Cardio', 'Burn'],
  },
  // Day 2
  {
    id: 'class-008',
    title: 'Sculpt & Tone',
    type: 'Sculpt',
    instructor: INSTRUCTORS[0],
    date: addDays(today, 2),
    time: '7:00 AM',
    duration: 45,
    totalSpots: 14,
    bookedSpots: [],
    price: 35,
    level: 'All Levels',
    description: 'Cams takes you through her signature sculpt routine. Get ready to shake.',
    tags: ['Sculpt', 'Cams', 'Full Body'],
  },
  {
    id: 'class-009',
    title: 'Slow Flow Yoga',
    type: 'Yoga',
    instructor: INSTRUCTORS[1],
    date: addDays(today, 2),
    time: '11:00 AM',
    duration: 60,
    totalSpots: 16,
    bookedSpots: [1, 2, 3, 4, 5, 6, 7, 8],
    price: 35,
    level: 'Beginner',
    description: "Deliberate, meditative movement. This one's for the days when you need to slow down and reset.",
    tags: ['Yoga', 'Slow', 'Recovery'],
  },
  {
    id: 'class-010',
    title: 'Reformer Foundations',
    type: 'Reformer',
    instructor: INSTRUCTORS[2],
    date: addDays(today, 2),
    time: '4:00 PM',
    duration: 50,
    totalSpots: 12,
    bookedSpots: [3, 6, 9],
    price: 35,
    level: 'Beginner',
    description: 'New to reformer? This class breaks down foundational movements so you can build with confidence.',
    tags: ['Reformer', 'Beginner', 'Foundations'],
  },
  // Day 3
  {
    id: 'class-011',
    title: 'HIIT + Flow',
    type: 'HIIT',
    instructor: INSTRUCTORS[1],
    date: addDays(today, 3),
    time: '9:00 AM',
    duration: 45,
    totalSpots: 16,
    bookedSpots: [1, 3, 5, 7],
    price: 35,
    level: 'Intermediate',
    description: 'The fan-favorite is back. Intervals, transitions, and beats that carry you through every rep.',
    tags: ['HIIT', 'Flow', 'Cardio'],
  },
  {
    id: 'class-012',
    title: 'Mat Pilates Total Body',
    type: 'Mat Pilates',
    instructor: INSTRUCTORS[0],
    date: addDays(today, 3),
    time: '7:00 PM',
    duration: 50,
    totalSpots: 14,
    bookedSpots: [],
    price: 35,
    level: 'All Levels',
    description: 'An evening mat session to reconnect with your body after a long day.',
    tags: ['Mat', 'Evening', 'Total Body'],
  },
  // Day 4
  {
    id: 'class-013',
    title: 'Full Body Reformer',
    type: 'Reformer',
    instructor: INSTRUCTORS[0],
    date: addDays(today, 4),
    time: '7:00 AM',
    duration: 50,
    totalSpots: 12,
    bookedSpots: [1, 2, 3, 4, 5, 6],
    price: 35,
    level: 'All Levels',
    description: 'Friday energy. Start your weekend strong on the reformer with Cams.',
    tags: ['Reformer', 'Friday', 'Energy'],
  },
  {
    id: 'class-014',
    title: 'Yoga & Restore',
    type: 'Yoga',
    instructor: INSTRUCTORS[2],
    date: addDays(today, 4),
    time: '10:00 AM',
    duration: 75,
    totalSpots: 16,
    bookedSpots: [2, 4],
    price: 35,
    level: 'All Levels',
    description: 'Restorative yoga with deep stretching and breathwork. The antidote to your week.',
    tags: ['Yoga', 'Restore', 'Breathwork'],
  },
];
